SELECT CONCAT(lat, latitude) AS combined_lat FROM dim_store_details;

ALTER TABLE dim_store_details
	ALTER COLUMN longitude SET DATA TYPE VARCHAR(255) USING longitude::VARCHAR,
	ALTER COLUMN locality SET DATA TYPE VARCHAR(255) USING locality::VARCHAR,
	ALTER COLUMN store_code SET DATA TYPE VARCHAR(255) USING store_code::VARCHAR,
	ALTER COLUMN staff_numbers SET DATA TYPE VARCHAR(255) USING staff_numbers::VARCHAR,
	ALTER COLUMN opening_date SET DATA TYPE DATE USING opening_date::DATE,
	ALTER COLUMN store_type SET DATA TYPE VARCHAR(255) USING store_type::VARCHAR,
	ALTER COLUMN latitude SET DATA TYPE NUMERIC USING latitude::NUMERIC,
	ALTER COLUMN country_code SET DATA TYPE VARCHAR(255) USING country_code::VARCHAR,
	ALTER COLUMN continent SET DATA TYPE VARCHAR(255) USING continent::VARCHAR;
