ALTER TABLE dim_date_times
	ALTER COLUMN "month" SET DATA TYPE VARCHAR(16) USING "month"::VARCHAR,
	ALTER COLUMN "year" SET DATA TYPE VARCHAR(16) USING "year"::VARCHAR,
	ALTER COLUMN "day" SET DATA TYPE VARCHAR(16) USING "day"::VARCHAR,
	ALTER COLUMN time_period SET DATA TYPE VARCHAR(16) USING time_period::VARCHAR,
	ALTER COLUMN date_uuid SET DATA TYPE UUID USING date_uuid::UUID;