CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

ALTER TABLE dim_users
	ALTER COLUMN first_name SET DATA TYPE VARCHAR(255) USING first_name::VARCHAR,
	ALTER COLUMN last_name SET DATA TYPE VARCHAR(255) USING last_name::VARCHAR,
	ALTER COLUMN date_of_birth SET DATA TYPE DATE USING date_of_birth::DATE,
	ALTER COLUMN country_code SET DATA TYPE VARCHAR(255) USING country_code::VARCHAR,
	ALTER COLUMN user_uuid SET DATA TYPE UUID USING user_uuid::UUID,
	ALTER COLUMN join_date SET DATA TYPE DATE USING join_date::DATE;